language: julia

os:
    - linux

julia:
    - 0.7
    - 1.0
    - nightly

matrix:
    allow_failures:
        - julia: nightly

addons:
    apt:
        packages:
            - hdf5-tools
    homebrew:
        packages:
            - hdf5
after_success:
    - julia -e 'cd(Pkg.dir("AsterReader")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
